# Generated by Django 3.2.15 on 2022-09-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_content_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
